///////////////////////////////////////////////////////////////////////////////
// SamplePostmanEchoServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_SamplePostmanEcho = 0x3F000000;
#define SRVNAME_SAMPLEPOSTMANECHO "SamplePostmanEcho"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_SamplePostmanEchoCSamplePostmanEchoModule = {0x20416eda,0x06d4,0x43b2,{0x81,0x0d,0x44,0xe8,0xd3,0x56,0xf0,0x13}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_SamplePostmanEchoModulesendHttpPostRequest = 0x00000002;
const PTCID PID_SamplePostmanEchoModulevalidMessageReceivedCnt = 0x00000003;
const PTCID PID_SamplePostmanEchoModulestatusCode = 0x00000004;
const PTCID PID_SamplePostmanEchoModuleerrorCnt = 0x00000005;
const PTCID PID_SamplePostmanEchoModulecontent = 0x00000006;
const PTCID PID_SamplePostmanEchoModuleHttpClient = 0x00000001;
const PTCID PID_SamplePostmanEchoModuleCyclicCaller = 0x00000007;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_
typedef CHAR STRING255[256];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
