///////////////////////////////////////////////////////////////////////////////
// SamplePostmanEchoClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "SamplePostmanEchoClassFactory.h"
#include "SamplePostmanEchoServices.h"
#include "SamplePostmanEchoVersion.h"
#include "SamplePostmanEchoModule.h"

BEGIN_CLASS_MAP(CSamplePostmanEchoClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_SamplePostmanEchoCSamplePostmanEchoModule, SRVNAME_SAMPLEPOSTMANECHO "!CSamplePostmanEchoModule", CSamplePostmanEchoModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CSamplePostmanEchoClassFactory::CSamplePostmanEchoClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_SAMPLEPOSTMANECHO));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(SamplePostmanEcho));
#endif //defined(TCDBG_UNIT_VERSION)
}

