///////////////////////////////////////////////////////////////////////////////
// SamplePostmanEchoModule.h
#pragma once

#include "SamplePostmanEchoInterfaces.h"
#include "Iot/TcIotDriversInterfaces.h"

class CSamplePostmanEchoModule 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
	, public ITcIotHttpResponse
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_SamplePostmanEchoCSamplePostmanEchoModule)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CSamplePostmanEchoModule();
	virtual	~CSamplePostmanEchoModule();

///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

	// ITcIotHttpResponse
	virtual HRESULT TCOMAPI OnHttpResponse(ULONG nInvokeId, ITcIotHttpResponseData* ipResponse);
	virtual HRESULT TCOMAPI OnHttpRequestFailed(ULONG nInvokeId, ETcIotHttpRequestError eErrorId);

///</AutoGeneratedContent>

protected:
	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	DECLARE_ITCOMOBJECT_SETSTATE();

///<AutoGeneratedContent id="Members">
	bool m_sendHttpPostRequest;
	ULONG m_validMessageReceivedCnt;
	USHORT m_statusCode;
	SHORT m_errorCnt;
	STRING255 m_content;
	ITcIotHttpClientPtr m_spHttpClient;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>
	bool m_prevSendHttpPostRequest;
	ULONG m_cntRequest;
};
